postcode_validation:
  range:
    int: [18906, 918146]
    len: [5, 6]
  drop_incorrect: false
  keep_validation_fields: true
  keep_formatted_postcode_field: true
  validation_field_names:
    candidate_postcode: CANDIDATE_POSTCODE
    extracted_postcode: EXTRACTED_POSTCODE
    correct_input_flag: CORRECT_INPUT_POSTCODE
    incorrect_reason: INCORRECT_INPUT_POSTCODE_REASON
    formatted_postcode: FORMATTED_POSTCODE

auto_identify_config:
  candidate_columns: null
  regex_pattern: "((?<!\\d)\\d{5,6}(?!\\d))"
  sample_size: 100
  success_threshold: 0.1
  seed: 42
